import type { Permission } from "@/lib/permissions/permissions";
import { permissions } from "@/lib/permissions/permissions";
import type { TenantRole } from "@/lib/stores/tenant.store";

const ownerPermissions: Permission[] = [
  permissions.tenantRead,
  permissions.tenantCreate,
  permissions.tenantUpdate,
  permissions.tenantManageMembers,
  permissions.tenantManagePlan,
  permissions.storeRead,
  permissions.storeUpdate,
  permissions.storePublish,
  permissions.storeUpdateBusinessHours,
  permissions.storeUpdateSEO,
  permissions.storeUpdateDiscovery,
  permissions.categoryRead,
  permissions.categoryCreate,
  permissions.categoryUpdate,
  permissions.categoryDelete,
  permissions.productRead,
  permissions.productCreate,
  permissions.productUpdate,
  permissions.productDelete,
  permissions.productUploadImage,
  permissions.inventoryRead,
  permissions.inventoryReadMovement,
  permissions.inventoryAdjust,
  permissions.inventoryUpdateThreshold,
  permissions.financeReadSummary,
  permissions.financeReadReport,
  permissions.financeReadExpense,
  permissions.financeCreateExpense,
  permissions.financeUpdateExpense,
  permissions.financeDeleteExpense,
  permissions.dashboardReadSummary,
  permissions.dashboardReadRecentOrders,
  permissions.dashboardReadLowStock,
  permissions.orderRead,
  permissions.orderReadDetail,
  permissions.orderUpdateStatus,
  permissions.orderUpdatePaymentStatus,
  permissions.orderCancel,
  permissions.posReadProduct,
  permissions.posOpenSession,
  permissions.posReadSession,
  permissions.posCreateTransaction,
  permissions.posReadTransaction,
  permissions.posCloseSession,
  permissions.posRefundTransaction
];

const managerPermissions: Permission[] = [
  permissions.tenantRead,
  permissions.storeRead,
  permissions.storeUpdateBusinessHours,
  permissions.storeUpdateSEO,
  permissions.storeUpdateDiscovery,
  permissions.categoryRead,
  permissions.categoryCreate,
  permissions.categoryUpdate,
  permissions.categoryDelete,
  permissions.productRead,
  permissions.productCreate,
  permissions.productUpdate,
  permissions.productUploadImage,
  permissions.inventoryRead,
  permissions.inventoryReadMovement,
  permissions.inventoryAdjust,
  permissions.inventoryUpdateThreshold,
  permissions.financeReadSummary,
  permissions.financeReadReport,
  permissions.financeReadExpense,
  permissions.financeCreateExpense,
  permissions.financeUpdateExpense,
  permissions.financeDeleteExpense,
  permissions.dashboardReadSummary,
  permissions.dashboardReadRecentOrders,
  permissions.dashboardReadLowStock,
  permissions.orderRead,
  permissions.orderReadDetail,
  permissions.orderUpdateStatus,
  permissions.orderUpdatePaymentStatus,
  permissions.orderCancel,
  permissions.posReadProduct,
  permissions.posOpenSession,
  permissions.posReadSession,
  permissions.posCreateTransaction,
  permissions.posReadTransaction,
  permissions.posCloseSession,
  permissions.posRefundTransaction
];

const rolePermissions: Record<TenantRole, Permission[]> = {
  owner: ownerPermissions,
  manager: managerPermissions,
  staff: [
    permissions.tenantRead,
    permissions.storeRead,
    permissions.categoryRead,
    permissions.productRead,
    permissions.inventoryRead,
    permissions.orderRead,
    permissions.orderReadDetail,
    permissions.orderUpdateStatus,
    permissions.posReadProduct,
    permissions.dashboardReadSummary,
    permissions.dashboardReadRecentOrders,
    permissions.dashboardReadLowStock
  ],
  cashier: [
    permissions.tenantRead,
    permissions.storeRead,
    permissions.categoryRead,
    permissions.posReadProduct,
    permissions.posOpenSession,
    permissions.posReadSession,
    permissions.posCreateTransaction,
    permissions.posReadTransaction,
    permissions.posCloseSession
  ],
  inventory_staff: [
    permissions.tenantRead,
    permissions.storeRead,
    permissions.categoryRead,
    permissions.productRead,
    permissions.inventoryRead,
    permissions.inventoryReadMovement,
    permissions.inventoryAdjust,
    permissions.inventoryUpdateThreshold,
    permissions.posReadProduct,
    permissions.dashboardReadSummary,
    permissions.dashboardReadLowStock
  ],
  courier_admin: [
    permissions.tenantRead,
    permissions.storeRead,
    permissions.dashboardReadSummary,
    permissions.dashboardReadRecentOrders
  ],
  driver: []
};

export function permissionsForRole(role: TenantRole) {
  return rolePermissions[role] ?? [];
}
