package permission

var rolePermissions = map[Role]map[Permission]bool{
	RoleOwner: {
		TenantRead:                true,
		TenantUpdate:              true,
		TenantManageMembers:       true,
		TenantManagePlan:          true,
		StoreRead:                 true,
		StoreUpdate:               true,
		StorePublish:              true,
		StoreUpdateBusinessHours:  true,
		StoreUpdateSEO:            true,
		StoreUpdateDiscovery:      true,
		CategoryRead:              true,
		CategoryCreate:            true,
		CategoryUpdate:            true,
		CategoryDelete:            true,
		ProductRead:               true,
		ProductCreate:             true,
		ProductUpdate:             true,
		ProductDelete:             true,
		ProductUploadImage:        true,
		InventoryRead:             true,
		InventoryReadMovement:     true,
		InventoryAdjust:           true,
		InventoryUpdateThreshold:  true,
		FinanceReadSummary:        true,
		FinanceReadReport:         true,
		FinanceReadExpense:        true,
		FinanceCreateExpense:      true,
		FinanceUpdateExpense:      true,
		FinanceDeleteExpense:      true,
		DashboardReadSummary:      true,
		DashboardReadRecentOrders: true,
		DashboardReadLowStock:     true,
		OrderRead:                 true,
		OrderReadDetail:           true,
		OrderUpdateStatus:         true,
		OrderUpdatePaymentStatus:  true,
		OrderCancel:               true,
		POSReadProduct:            true,
		POSOpenSession:            true,
		POSReadSession:            true,
		POSCreateTransaction:      true,
		POSReadTransaction:        true,
		POSCloseSession:           true,
		POSRefundTransaction:      true,
	},
	RoleManager: {
		TenantRead:                true,
		StoreRead:                 true,
		StoreUpdateBusinessHours:  true,
		StoreUpdateSEO:            true,
		StoreUpdateDiscovery:      true,
		CategoryRead:              true,
		CategoryCreate:            true,
		CategoryUpdate:            true,
		CategoryDelete:            true,
		ProductRead:               true,
		ProductCreate:             true,
		ProductUpdate:             true,
		ProductUploadImage:        true,
		InventoryRead:             true,
		InventoryReadMovement:     true,
		InventoryAdjust:           true,
		InventoryUpdateThreshold:  true,
		FinanceReadSummary:        true,
		FinanceReadReport:         true,
		FinanceReadExpense:        true,
		FinanceCreateExpense:      true,
		FinanceUpdateExpense:      true,
		FinanceDeleteExpense:      true,
		DashboardReadSummary:      true,
		DashboardReadRecentOrders: true,
		DashboardReadLowStock:     true,
		OrderRead:                 true,
		OrderReadDetail:           true,
		OrderUpdateStatus:         true,
		OrderUpdatePaymentStatus:  true,
		OrderCancel:               true,
		POSReadProduct:            true,
		POSOpenSession:            true,
		POSReadSession:            true,
		POSCreateTransaction:      true,
		POSReadTransaction:        true,
		POSCloseSession:           true,
		POSRefundTransaction:      true,
	},
	RoleStaff: {
		TenantRead:                true,
		StoreRead:                 true,
		CategoryRead:              true,
		ProductRead:               true,
		InventoryRead:             true,
		OrderRead:                 true,
		OrderReadDetail:           true,
		OrderUpdateStatus:         true,
		POSReadProduct:            true,
		DashboardReadSummary:      true,
		DashboardReadRecentOrders: true,
		DashboardReadLowStock:     true,
	},
	RoleCashier: {
		TenantRead:           true,
		StoreRead:            true,
		CategoryRead:         true,
		POSReadProduct:       true,
		POSOpenSession:       true,
		POSReadSession:       true,
		POSCreateTransaction: true,
		POSReadTransaction:   true,
		POSCloseSession:      true,
	},
	RoleInventoryStaff: {
		TenantRead:               true,
		StoreRead:                true,
		CategoryRead:             true,
		ProductRead:              true,
		InventoryRead:            true,
		InventoryReadMovement:    true,
		InventoryAdjust:          true,
		InventoryUpdateThreshold: true,
		POSReadProduct:           true,
		DashboardReadSummary:     true,
		DashboardReadLowStock:    true,
	},
	RoleCourierAdmin: {
		TenantRead:                true,
		StoreRead:                 true,
		DashboardReadSummary:      true,
		DashboardReadRecentOrders: true,
	},
}

func Allowed(role string, permission Permission) bool {
	permissions, ok := rolePermissions[Role(role)]
	if !ok {
		return false
	}

	return permissions[permission]
}
